// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD5foUEdiF15I9gEoA15NN-ObGS0GIuHw',
    appId: '1:333165022104:web:ccf54b64a46339e202f9ed',
    messagingSenderId: '333165022104',
    projectId: 'renat-crypto-project',
    authDomain: 'renat-crypto-project.firebaseapp.com',
    storageBucket: 'renat-crypto-project.firebasestorage.app',
    measurementId: 'G-DMXYN52VNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxEEbbji3YoY4j5WrHTKczSHZ3bG-cjWs',
    appId: '1:333165022104:android:ed1707f6d687b6db02f9ed',
    messagingSenderId: '333165022104',
    projectId: 'renat-crypto-project',
    storageBucket: 'renat-crypto-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC53pTTG6G-eykk8cuSaGSJVq36oGyuNmc',
    appId: '1:333165022104:ios:f546433447458c8002f9ed',
    messagingSenderId: '333165022104',
    projectId: 'renat-crypto-project',
    storageBucket: 'renat-crypto-project.firebasestorage.app',
    iosBundleId: 'com.example.renatCryptoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC53pTTG6G-eykk8cuSaGSJVq36oGyuNmc',
    appId: '1:333165022104:ios:f546433447458c8002f9ed',
    messagingSenderId: '333165022104',
    projectId: 'renat-crypto-project',
    storageBucket: 'renat-crypto-project.firebasestorage.app',
    iosBundleId: 'com.example.renatCryptoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD5foUEdiF15I9gEoA15NN-ObGS0GIuHw',
    appId: '1:333165022104:web:560a24b61a2d711302f9ed',
    messagingSenderId: '333165022104',
    projectId: 'renat-crypto-project',
    authDomain: 'renat-crypto-project.firebaseapp.com',
    storageBucket: 'renat-crypto-project.firebasestorage.app',
    measurementId: 'G-NJCDK0Z0BJ',
  );
}
